/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "palindrome.h"

bool_t
xdr_word (XDR *xdrs, word *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->word, 100))
		 return FALSE;
	return TRUE;
}
