/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PALINDROME_H_RPCGEN
#define _PALINDROME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct word {
	char *word;
};
typedef struct word word;

#define ADD_PROG 0x123456
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define is_palindrome 1
extern  int * is_palindrome_1(word *, CLIENT *);
extern  int * is_palindrome_1_svc(word *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define is_palindrome 1
extern  int * is_palindrome_1();
extern  int * is_palindrome_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_word (XDR *, word*);

#else /* K&R C */
extern bool_t xdr_word ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PALINDROME_H_RPCGEN */
