/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "palindrome.h"

int *is_palindrome_1_svc(word *argp, struct svc_req *rqstp) {
    static int result;

    result = check_palindrome(argp->word);

    return &result;
}

int check_palindrome(char *string) {

    char *ptr, *rev;
    ptr = string;

    while (*ptr != '\0') {
        ++ptr;
    }
    --ptr;
    for (rev = string; ptr >= rev;) {
        if (*ptr == *rev) {
            --ptr;
            rev++;
        } else
            break;
    }
    if (rev > ptr)
        return 1;

    return 0;
}